import { Footer } from "@/_components/footer";
import { Header } from "@/_components/header";
import Provider from "@/lib/trpc/provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sankalpa USA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex min-h-screen w-full">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="flex flex-col grow w-full overflow-y-auto">
        <Provider>
          <ClerkProvider>
            <Header />
            {children}
            <Footer />
          </ClerkProvider>
        </Provider>
      </body>
    </html>
  );
}
